### ISSUE TITLE
Is it possible to make things simpler

### ISSUE THREAD

**Issue by AliceRixte** [youqad/Coherence-of-Heyting-arithmetic#1]
I made a very complicated proof of HAn_Sn and I wonder if I missed something. Did I?

**Comment by youqad** [comment]
Good work! I simplified your proof as much as I could, you can have a look at it now.
You didn't miss anything, it was well written, but if I had to stress a key point, I would say that you may happen to go into too much detail to some extent: don't forget that we can resort to tactics like `auto`, `eauto` and `intuition` that automate lots of boring details and considerably simplify things: elementary tactics like `reflexivity `, `easy`, etc... (which make the proof more verbose) can be completely avoided thanks to these :-)

**Comment by AliceRixte** [comment]
Thanks !
