### ISSUE TITLE
Error: Unknown interpretation for notation "_ <=? _".

### ISSUE THREAD

**Issue by farzadhtg** [youqad/Coherence-of-Heyting-arithmetic#2]
I get an error when I compile the following code:

Ltac break := match goal with
 | |- context [ ?x <=? ?y ] => destruct (Nat.leb_spec x y)
 | |- context [ ?x ?= ?y ] => destruct (Nat.compare_spec x y)
end.

would you mind tell me what is wrong?

**Comment by youqad** [comment]
Hmm.... it's weird: I have no such compiling problem on my side: you're talking about the definition of the tactic `break` which is defined at the beginning of `Heyting.v`, aren't you? Are you sure your version of Coq is updated? What does the command

```sh
coqtop -v
```

yield in a shell?

**Comment by farzadhtg** [comment]
Yes, I'm talking about tactic "break".

output:
The Coq Proof Assistant, version 8.4pl4 (November 2015)
compiled on Nov 04 2015 12:56:53 with OCaml 4.02.3

**Comment by AliceRixte** [comment]
I have this 
The Coq Proof Assistant, version 8.5pl1 (June 2016)
compiled on Jun 27 2016 14:31:9 with OCaml 4.02.3

So maybe you should update your coq version.

**Comment by farzadhtg** [comment]
Do you know how can I update my coq on Ubuntu?

**Comment by AliceRixte** [comment]
try this :
sudo apt upgrade coq

**Comment by farzadhtg** [comment]
it doesn't update :/

**Comment by youqad** [comment]
@farzadhtg If you've installed it with Opam, try `opam upgrade`

**Comment by farzadhtg** [comment]
I tried it yesterday too, but didn’t work.
I think I should install windows and try coq on it.

**Comment by youqad** [comment]
Have you tried `opam update` first before `opam upgrade`? Installing windows to use coq is using a sledgehammer to crack a nut though 😅

**Comment by farzadhtg** [comment]
I removed everything and install again on ubuntu :) 
I don't know the reason, but It's OK right now and finally, I can compile the code :)
