### ISSUE TITLE
How to use "apply <-" with "with" ? 

### ISSUE THREAD

**Issue by AliceRixte** [youqad/Coherence-of-Heyting-arithmetic#8]
All is in the title : when you type
`apply <- finterp_misc with t .`
you always get "synntax error blablabla".

Any clue?

**Comment by AliceRixte** [comment]
I couldn't see the documentation of apply because the inria server seems down.

**Comment by farzadhtg** [comment]
Did you try “Search(apply)” in coq?

**Comment by AliceRixte** [comment]
Doesn't work, sorry :(

**Comment by youqad** [comment]
@141592653 The syntax is rather:

```coq
apply <- finterp_misc with (t:=t).
```

or if you want to specify implicit arguments:

```coq
apply (@finterp_misc _ t _) 
```

But I can't find where you used this tactic: is it still in the code?

**Comment by AliceRixte** [comment]
I did 2 implications ;) thanks, I will simplifu it.
